### ISSUE TITLE
Building the project leaves the git index dirty

### ISSUE THREAD

**Issue by athei** [paritytech/pallet-contracts-waterfall#51]
I just tried building the project by calling `./build`. Without any modification on my side this dirties my git index:
```
modified:   contracts/assemblyscript/flipper/package.json
modified:   contracts/assemblyscript/flipper/yarn.lock
```

This makes working with this project an unpleasant experience. The root cause seems to be these line in build.sh:
`yarn add assemblyscript`

Why not check in the proper version with the yarn.lock and be done? I noticed that there is a comment for this line that this is some kind of workaround. I think we need to check whether it is still needed.

**Comment by Stefie** [comment]
It used to be a workaround before  the last stable major release of Assemblyscript and  I haven't checked it since. The problem was, that assemblyscript didn't get installed at all from the yarn lock if the latest version was different to the one in the lock file.
It's possible that it has been fixed  since I last checked.

**Comment by Stefie** [comment]
We added it to make the Gitlab CI run because it failed commonly because of the missing dependency. I updated the AS version and the dependencies, we can give it a try. If the CI fails because of this again, we need to add it, because the CI is more important than a local git index

**Comment by athei** [comment]
Is the ci even executing the `build.sh`? Isn't it taking its commands directly from the `.gitlab-ci.yml`?

**Comment by pepyakin** [comment]
@athei you seems to be right, looks like `.gitlab-ci.yml` just duplicates `./build.sh` for some reason. There is no comment left, so I guess we should ask @TriplEight : is there any particular reason for that? It would have been great if the local build and the CI build did the same and didn't require us to change two places when we add or remove a new test contract.

**Comment by Stefie** [comment]
@athei  and me talked about it in person last friday, I forgot to update the ticket. 
It's still a WIP for @TriplEight  and we might just need to invest a day or two to get everything working & testing like we want it to and to be notified when it fails...
Some things are just still a little off. 

I think the original issue, the additional `yarn add assemblyscript` might be solved, but we also need Denis to test that in the CI

**Comment by TriplEight** [comment]
AFAIR we left CI as it looks like right now because of some unresolved issue with Substrate API (and something else). Initially it was supposed to be parallelized. 
I can rewrite it so it would launch the scripts, but that way CI output will be less informative. It might become a problem since right now we have only one huge job.

**Comment by Stefie** [comment]
Yeah, I remember the same. I just changed the version of the Polkadot JS API to latest beta last week, so that's up to date now and seems to be working.
I don't know if you read the Riot chat yesterday, but the points I mentioned there are still open.

- The notifications are not working properly
- it's not using the latest version of ink, but the one we're referring to in the /lib/ folder
- It's not running every night
- it's not running on every merged Substrate PR
- I'm not sure if it's using the latest version of cargo-contract
- The build.sh script we're using locally is different to the one used on the server

I think it would really make sense to sit together/ have a call some time this week to pin down what we actually want/ expect from this repo

**Comment by TriplEight** [comment]
Yes, @Stefie, sure. BTW I've changed the larger part of CI config to running the build script. https://github.com/paritytech/pallet-contracts-waterfall/pull/55
